kts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import django.contrib.auth.views
import tasks.views

urlpatterns = [

    # index
    url(r'^$', tasks.views.list),





    # accounts
    url(r'^accounts/login/$', django.contrib.auth.views.login,
        dict(template_name='login.html'), name='login'),
    url(r'^accounts/password_reset/$',
        django.contrib.auth.views.password_reset, name='password_reset'),
    # url(r'^accounts/profile/$', 'django.contrib.auth.views.profile'),





    # tasks
    url(r'^tasks/', include('tasks.urls')),





    # admin
    url(r'^admin/', admin.site.urls),
]

tasks/urls.py
from django.conf.urls import url
from . import views


app_name = 'tasks'
urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^tags/(?P<tag>[^ ]+)$', views.listwithtag, name='listwithtag'),

    # url(r'^add$', views.add, name='add'),
    url(r'^fastadd$', views.fastadd, name='fastadd'),

    # url(r'^(?P<task_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<task_id>\d+)/edit$', views.edit, name='edit'),
    url(r'^(?P<task_id>\d+)/delete$', views.delete, name='delete'),
    url(r'^(?P<task_id>\d+)/convertto/(?P<identify>\w+)$',
        views.convertto, name='convertto'),




    # util
    url(r'^csv/', views.csv, name='csv'),
    url(r'^importall$', views.importall, name='importall'),
]

tasks/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

import abc


class AbstractTaskState(object):
    __meta__ = abc.ABCMeta


class TaskInit(AbstractTaskState):

    @staticmethod
    def avaiop():
        return ['devel']

    @staticmethod
    def identify():
        return 'init'

    @staticmethod
    def name():
        return 'Put back'

    @staticmethod
    def precheck(ins):
        pass

    @staticmethod
    def op(ins):
        return ins.dev

    @staticmethod
    def alter_op(ins):
        return None  # ins.dev

    @staticmethod
    def step():
        return 0


class TaskDevel(AbstractTaskState):

    @staticmethod
    def avaiop():
        return ['test', 'init']

    @staticmethod
    def identify():
        return 'devel'

    @staticmethod
    def name():
        return 'Devel'

    @staticmethod
    def precheck(ins):
        assert ins.dev

    @staticmethod
    def op(ins):
        return ins.dev

    @staticmethod
    def alter_op(ins):
        return ins.test

    @staticmethod
    def step():
        return 1


class TaskTest(AbstractTaskState):

    @staticmethod
    def avaiop():
        return ['finish', 'devel']

    @staticmethod
    def identify():
        return 'test'

    @staticmethod
    def name():
        return 'Test'

    @staticmethod
    def precheck(ins):
        assert ins.test

    @staticmethod
    def op(ins):
        return ins.test

    @staticmethod
    def alter_op(ins):
        return ins.dev

    @staticmethod
    def step():
        return 2


class TaskFinish(AbstractTaskState):

    @staticmethod
    def avaiop():
        return ['test']

    @staticmethod
    def identify():
        return 'finish'

    @staticmethod
    def name():
        return 'Finish'

    @staticmethod
    def precheck(ins):
        pass

    @staticmethod
    def op(ins):
        return ins.test

    @staticmethod
    def alter_op(ins):
        return ins.dev

    @staticmethod
    def step():
        return 3


class TaskDead(AbstractTaskState):

    @staticmethod
    def avaiop():
        return ['init']

    @staticmethod
    def identify():
        return 'dead'

    @staticmethod
    def name():
        return 'Dead'

    @staticmethod
    def precheck(ins):
        pass

    @staticmethod
    def op(ins):
        return None

    @staticmethod
    def step():
        return 0


class Tag(models.Model):
    name = models.CharField(max_length=32)

    def __unicode__(self):
        return self.name


class Value(models.Model):
    tag = models.ForeignKey('Tag')  # ,related_name='values')
    task = models.ForeignKey('Task')
    value = models.CharField(max_length=64, blank=True, default='')


class Task(models.Model):

    available_state = {
        'init': TaskInit,
        'devel': TaskDevel,
        'test': TaskTest,
        'finish': TaskFinish,
        'dead': TaskDead,
    }

    title = models.CharField(max_length=64, null=False, blank=False)
    create_date = models.DateTimeField(auto_now_add=True)
    state = models.CharField(max_length=16, blank=False, null=False, choices=(
        ('init', u'init'),
        ('devel', u'devel'),
        ('test', u'test'),
        ('finish', u'finish'),
        ('dead', u'dead'),), default='init')
    dev = models.ForeignKey(User, null=True, default=None,
                            related_name='my_dev_tasks')
    test = models.ForeignKey(
        User, null=True, default=None,
        related_name='my_test_tasks')
    desc = models.TextField(blank=True, null=False, default='')

    def __unicode__(self):
        return u'[%s] %s' % (self.state, self.title)

    @property
    def state_obj(self):
        return self.available_state[self.state]

    @property
    def available_op(self):
        return [self.available_state[sn] for sn in self.available_state[self.state].avaiop()]

    @property
    def op(self):
        return self.available_state[self.state].op(self)

    @property
    def alter_op(self):
        return self.available_state[self.state].alter_op(self)

    def convert(self, state_name):
        clz = self.available_state[state_name]
        clz.precheck(self)

        self.state = clz.identify()
        self.save()

tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse

from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import Task, Tag


from django.forms import ModelForm
from cStringIO import StringIO
import csv as csvm


class TaskForm(ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'dev', 'test', 'desc']


@login_required
def list(request):
    tags = Tag.objects.all()
    tasks = Task.objects.exclude(
        state='dead'
    ).exclude(
        state='finish'
    )
    tasks = sorted(tasks,
                   key=lambda task: u'%20s-%20s' % (10 - task.state_obj.step(), task.op))
    return render(request, 'list.html', dict(tags=tags, tasks=tasks))


@login_required
def listwithtag(request, tag):
    if tag == 'untagged':
        pass
    else:
        tag = get_object_or_404(Tag, name=tag)
        values = tag.value_set.all()
        tasks = []
        for value in values:
            tasks.append(value.task)
    tags = Tags.objects.annotate(Count('value_set'))
    return render(request, 'list.html', {'tasks': tasks, 'tags': tags})


@login_required
def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    return render(request, 'detail.html', {'task': task})


@login_required
def edit(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task.save()
    else:
        form = TaskForm(instance=task)
    return render(request, 'edit.html', {'task': task, 'form': form})


@login_required
def delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.convert('dead')

    return redirect(reverse('tasks:list'))


@login_required
def convertto(request, task_id, identify):
    task = get_object_or_404(Task, pk=task_id)
    task.convert(identify)  # 'dead')

    prev_url = request.META.get('HTTP_REFERER', reverse('tasks:list'))

    return redirect(prev_url)  # reverse('tasks:edit', args=[task.id]))


@login_required
def fastadd(request):
    if request.method == 'POST':
        title = request.POST['title']
        task = Task(title=title)
        task.save()
        return redirect(reverse('tasks:list'))


@login_required
def importall(request):
    if request.method == 'POST':
        txt = request.POST['titles']
        for title in txt.split('\n'):
            task = Task(title=title)
            task.save()
        return redirect(reverse('tasks:list'))
    else:
        return render(request, 'importall.html')


@login_required
def csv(request):
    sio = StringIO()
    try:
        writer = csvm.DictWriter(
            sio, fieldnames=['state', 'title', 'dev', 'test', 'createdate'])
        writer.writeheader()
        alltasks = Task.objects.exclude(state='dead').exclude(state='finish')
        for task in alltasks:
            linearr = {
                'state': task.state,
                'title': task.title,
                'dev': task.dev,
                'test': task.test,
                'createdate': task.create_date}
            strarr = {k: unicode(o).encode('utf-8')
                      for k, o in linearr.items()}
            writer.writerow(strarr)
        return HttpResponse(sio.getvalue(), content_type='application/csv')
    finally:
        sio.close()

tasks/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<title>kts</title>
	</head>
	<body>
		<h1>kts <font size="2">{% now 'Y-m-d' %}</font></h1>
		<a href="{%url 'tasks:list'%}">任务列表</a>
		<hr>
		{% block content %}
		{% endblock %}
		<hr>
		kts 0.1, by yjzeng
	</body>
</html>

tasks/templates/edit.html
{% extends "base.html" %}
{% block content %}
	<h1>{{task.title}}</h1>
	<ul>
		<li>{{task.state}}</li>
		{% for op in task.available_op %}
			<li><a href="{%url 'tasks:convertto' task.id op.identify%}">转{{op.name}}</a></li>
		{% endfor %}
	</ul>
	{% if error_message %}
		<p>{{error_message}}</p>
	{% endif %}
	<form action="{%url 'tasks:edit' task.id%}" method="POST">
		{%csrf_token%}
		<table>
			{{form}}
			<tr>
				<td>
				</td>
				<td>
					<input type="submit" name="" value="保存">
				</td>
			</tr>
		</table>
	</form>
	<ul>
		<li>
			<a href="{%url 'tasks:delete' task.id%}">删除</a>
		</li>
	</ul>
{% endblock %}

tasks/templates/importall.html
{% extends "base.html" %}
{% block content %}
	{% if error_message %}
		<p>{{error_message}}</p>
	{% endif %}
	<form action="{%url 'tasks:importall'%}" method="POST">
		{%csrf_token%}
<table>
<tr>
<td><label>Titles:</label></td>
<td>		<textarea name="titles"></textarea></td>
</tr>
<tr><td></td>
	<td>	<input type="submit" name="" value="添加"></td>
</tr>
</table>
	</form>
{% endblock %}

tasks/templates/list.html
{% extends "base.html" %}
{% block content %}
	{% regroup tasks by state as status %}
	<ul>
		<li>
			<form method="POST" action="{%url 'tasks:fastadd' %}">
				{% csrf_token%}
				<input type="text" name="title"><input type="submit" name="">
			</form>
		</li>
		{% for s_tasks in status %}
			<li> {{s_tasks.grouper}}
				<ul>
					{% regroup s_tasks.list by op as ops %}
					{% for op in ops %}
						<li> {{op.grouper|default_if_none:'----' }}
							<ul>
								{% for task in op.list %}
									<li>
										<a href="{% url 'tasks:edit' task.id %}">{{task.title}}</a><font size="1"><i>{{task.alter_op|default_if_none:''}}</i></font>
										{% for op in task.available_op %}
											[<a href="{%url 'tasks:convertto' task.id op.identify%}">{{op.name}}</a>]
										{% endfor %}
									</li>
								{% endfor %}
							</ul>
						</li>
					{% endfor %}
				</ul>
			</li>
		{% endfor %}
	</ul>
	<ul>
		<li><a href="{% url 'tasks:importall' %}">批量导入</a></li>
		<li><a href="{%url 'tasks:csv'%}{% now 'Ymd' %}.csv">下载csv</a></li>
	</ul>
{% endblock %}

tasks/templates/login.html
{% extends "base.html" %}
{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
            please login with an account that has access.</p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>
        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
    {# Assumes you setup the password_reset view in your URLconf #}
    <p><a href="{% url 'password_reset' %}">Lost password?</a></p>
{% endblock %}